title: Python Notes
description: You tell AI what you want. AI writes Python code. You run it. Problems get solved.
theme: primer
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - docs/
