title: Python Notes
markdown: kramdown
highlighter: rouge
remote_theme: pages-themes/hacker@v0.2.0
show_downloads: false
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - docs/
