title: Python Notes
description: You tell AI what you want. AI writes Python code. You run it. Problems get solved.
markdown: kramdown
highlighter: rouge
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - docs/
